/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    'bg-black',
    'text-white',
    'font-bold',
    'tracking-tight',
    'text-4xl',
    'md:text-5xl',
    'lg:text-6xl',
    'text-3xl',
    'md:text-4xl',
    'lg:text-5xl',
    'text-2xl',
    'md:text-3xl',
    'lg:text-4xl',
    'inline-flex',
    'items-center',
    'justify-center',
    'rounded-md',
    'text-sm',
    'font-medium',
    'transition-colors',
    'focus-visible:outline-none',
    'focus-visible:ring-2',
    'focus-visible:ring-offset-2',
    'disabled:pointer-events-none',
    'disabled:opacity-50',
    'bg-indigo-600',
    'hover:bg-indigo-700',
    'bg-slate-800',
    'hover:bg-slate-700',
    'mx-auto',
    'max-w-7xl',
    'px-4',
    'sm:px-6',
    'lg:px-8',
    'bg-slate-800/70',
    'backdrop-blur-md',
    'rounded-2xl',
    'border',
    'border-slate-700/50',
    'hover:shadow-[0_0_15px_rgba(59,130,246,0.2)]',
    'hover:border-blue-500/50',
    'hover:transform',
    'hover:scale-105',
    'transition-all',
    'duration-300',
  ],
} 