export const subscriptionRules = {
  FREE: {
    fitsPreview: true,
    projectSlots: 3,
    imageUploadsPerProject: 10,
    aiTools: 'Limited (e.g. once per week)',
    highResDownloads: false,
    communityWall: 'Read-only',
    photoOfTheDay: false,
    storageRetention: 14,
    priorityQueue: false,
    multiDeviceAccess: true,
    support: 'Community-only',
    betaFeatures: false,
    staffAdminControls: false,
    teamWorkspace: false,
  },
  Monthly: {
    fitsPreview: true,
    projectSlots: 25,
    imageUploadsPerProject: 'Unlimited',
    aiTools: true,
    highResDownloads: true,
    communityWall: 'Post, vote, comment',
    photoOfTheDay: true,
    storageRetention: 180,
    priorityQueue: true,
    multiDeviceAccess: true,
    support: 'Standard support',
    betaFeatures: false,
    staffAdminControls: false,
    teamWorkspace: false,
  },
  Annual: {
    fitsPreview: true,
    projectSlots: 25,
    imageUploadsPerProject: 'Unlimited',
    aiTools: true,
    highResDownloads: true,
    communityWall: 'Post, vote, comment',
    photoOfTheDay: true,
    storageRetention: 180,
    priorityQueue: true,
    multiDeviceAccess: true,
    support: 'Standard support',
    betaFeatures: false,
    staffAdminControls: false,
    teamWorkspace: false,
  },
  Super: {
    fitsPreview: true,
    projectSlots: 'Unlimited',
    imageUploadsPerProject: 'Unlimited',
    aiTools: true,
    highResDownloads: true,
    communityWall: 'All + moderation tools',
    photoOfTheDay: true,
    storageRetention: 365,
    priorityQueue: 'Highest priority',
    multiDeviceAccess: true,
    support: 'Priority support (staff channel)',
    betaFeatures: true,
    staffAdminControls: true,
    teamWorkspace: true,
  },
}; 